config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # verb "path", to: "controller#action"#

  get "tasks/list", to: "tasks#list"

  # below 2 routes are for post. first one finds the task, second posts
  get "tasks/new", to: "tasks#new", as: "new_task"
  post "tasks", to: "tasks#create"

  # below 2 routes are for edit. first one finds the task, second patches
  get "tasks/:id/edit", to: "tasks#edit", as: "update_task"
  patch "tasks/:id", to: "tasks#update"

  # delete
  delete "tasks/:id", to: "tasks#destroy"


  # show one task
  get "tasks/:id", to: "tasks#show", as: "task"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

def list
  @tasks = Task.all
end

def show
  @task = Task.find(params[:id])
end

def new
  @task = Task.new
end

def create
  @task = Task.new(task_params)
  @task.save
  # No need for app/views/restaurants/create.html.erb
  redirect_to task_path(@task)
end

def find
  @task = Task.find(params[:id])
end

def edit
  @task = Task.find(params[:id])
end

def update
  @task = Task.find(params[:id])
  @task.update(task_params)
  # No need for app/views/restaurants/update.html.erb
  redirect_to task_path(@task)
end

def destroy
  @task = Task.find(params[:id])
  @task.destroy
  redirect_to tasks_list_path, status: :see_other
end

private

# This is a strong param to keep the data safe
def task_params
  params.require(:task).permit(:title, :details)
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body class="container mt-5">
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h3>Edit <%= @task.title %> Task</h3>

<%= form_for(@task) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :details %>
    <%= form.text_field :details %>
  </div>
  <%= form.submit "Edit Task" %>
<% end %>

app/views/tasks/list.html.erb
<h3>My Tasks</h3>


<div class= "mt-3">
  <% @tasks.each do |task| %>
  <input type="checkbox" name="task" value="task">
  <label for="task"><a href="http://localhost:3000/tasks/<%= task.id %>"><%= task.title %></a></label><br>
  <% end %>
</div>


<div>
<%= link_to "Add Task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<%= form_for(@task) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :details %>
    <%= form.text_field :details %>
  </div>
  <%= form.submit "Add Task" %>
<% end %>



<div>
  <%= link_to "All Tasks", tasks_list_path %>
</div>

app/views/tasks/show.html.erb
<h4>Task Details</h4>

<div class="mt-4">
<h6><%= @task.title %></h6>
<h6><%= @task.details %></h6>
</div>


<div>
  <%= link_to "All Tasks", tasks_list_path %>
</div>

<%= link_to "Edit Task", update_task_path %>

<%= link_to "Delete",
  task_path(@task),
  data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>